AWSTemplateFormatVersion: '2010-09-09'

Resources:

  WebSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Permitir HTTP

      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

  WebServer:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0c02fb55956c7d316
      InstanceType: t2.micro

      SecurityGroupIds:
        - !Ref WebSecurityGroup

      UserData:
        Fn::Base64: |
          #!/bin/bash
          yum update -y
          yum install -y httpd

          systemctl enable httpd
          systemctl start httpd

          cat > /var/www/html/index.html <<EOF
          <!DOCTYPE html>
          <html>
          <head>
              <title>Examen Final</title>
              <style>
                  body {
                      background-color: #0f172a;
                      color: white;
                      text-align: center;
                      margin-top: 100px;
                      font-family: Arial, sans-serif;
                  }
              </style>
          </head>
          <body>

              <h1>CARLOS DANIEL TORRES MENESES</h1>
              <h2>TU CODIGO ESTUDIANTIL</h2>
              <h3>Examen Final Arquitectura de Computadores</h3>

              <script>
                  console.log("Examen Final AWS");
              </script>

          </body>
          </html>
          EOF
          